server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web #请求方式,默认以http的方式向zipkin server发送追踪数据
    sleuth:
      sampler:
        # 采样率值介于 0 到 1 之间 1则表示全部采样
        probability: 1

eureka:
  client:
    # 表示是否将自己注册进Eureka Server默认为 true
    register-with-eureka: true
    # 是否从Eureka Server住区已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      # 单机模式
      defaultZone: http://eureka7001.com:7001/eureka/

