server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wuwuwuzzz/spring-cloud-config
          search-paths:
            - spring-cloud-config
      label: master
  rabbitmq:
    host: localhost
    # 15672是Web管理界面的端口，5672是mq访问的端口
    port: 5672
    stream:
      username: guest
      password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
