server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
      ribbon:
        enable: false

#消费者将要去访问的微服务者名称
service-url:
  nacos-user-service: http://nacos-payment-provider

management:
  endpoints:
    web:
      exposure:
        incloud: '*'

feign:
  sentinel:
    enabled: true



