server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        # 表示定义的名称，用于bindings整合
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        # 这个名字是一个通道的名称
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: atguiguA

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/