server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 表示是否将自己注册进Eureka Server默认为 true
    register-with-eureka: true
    # 是否从Eureka Server住区已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      # 单机模式
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  hystrix:
    # Feign启用断路器，默认为FALSE
    enabled: false
  client:
    config:
      # 针对所有的服务
      default:
        # Feign的连接建立超时时间，默认为10秒
        connectTimeout: 5000
        # Feign的请求处理超时时间，默认为60秒
        readTimeout: 5000

logging:
  level:
    # root日志以WARN级别输出
    root: WARN
    # com.saint.feign.client包下的日志以DEBUG级别输出
    com.atguigu.springcloud.service.PaymentFeignService: DEBUG